import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:market/screens/ProductScreen.dart';

class ButcherCategory extends StatefulWidget {
  final name;

  const ButcherCategory({Key? key, required this.name}) : super(key: key);

  @override
  State<ButcherCategory> createState() => _ButcherCategoryState();
}

class _ButcherCategoryState extends State<ButcherCategory> {
  _buildProductCard(product) {
    return GestureDetector(
      onTap: () {
        Navigator.of(context).push(CupertinoPageRoute(builder: (BuildContext context) => ProductScreen(product: product,)));
      },
      child: Container(
        decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20),
            color: Colors.black,
            boxShadow: [
              BoxShadow(
                  color: Colors.grey.withOpacity(0.2),
                  blurRadius: 4,
                  spreadRadius: 2
              ),
            ],
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Hero(
              tag: product['id'],
              child: Container(
                width: 120,
                height: 80,
                decoration: BoxDecoration(
                  image: DecorationImage(
                    image: NetworkImage(product['img']),
                    fit: BoxFit.cover,
                  ),
                  borderRadius: BorderRadius.circular(12)
                ),
              ),
            ),
            SizedBox(height: 12,),
            Text(product['name'], style: TextStyle(color: Colors.white, fontSize: 14),),
            SizedBox(height: 12,),
            Text(product['price'], style: TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.bold),),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: GridView.count(
        crossAxisCount: 2,
        mainAxisSpacing: 20,
        crossAxisSpacing: 10,
        padding: EdgeInsets.only(top: 16, left: 8, right: 8),
        children: [
          _buildProductCard({ "id": "1", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "2", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "3", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "4", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "5", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "6", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "7", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }), 
          _buildProductCard({ "id": "8", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "9", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "10", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "11", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "12", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "13", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
          _buildProductCard({ "id": "14", "name": "Kasap Sucuğu 1KG", "price": "699.99TL", "img": "https://www.mintekshome.com/cali-kasabi-kangal-sucuk-1-kg-9238-39-B.jpg", "description": "Sucuk (Azerice: sucuk, Kazakça:  Шұжық , Kırgızca:  Чучук [1][2], Korece:  수주크 , Fransızca: soudjouk, Arapça: سجق; sucuk, Kürtçe: benî), başlıca Balkanlar, Orta Doğu ve Orta Asya'da tüketilen, şişirilip kurutulmuş bağırsak içine baharatlı et kıyması doldurularak yapılan bir tür fermante et ürünüdür. Uzun raf ömrüne sahip bir tüketim malzemesidir. Ekonomik olarak satın alınmasını kolaylaştırmak üzere küçükbaş hayvan eti de sıkça karıştırılır. Yapımında sakatat kullanılmayan sucuğun Orta Çağdan beri farklı şekillerde yapıldığı bilinmektedir.[3] Sucuk, Kazakistan ve Kırgızistan'da at eti kullanılarak da yapılmaktadır.[4][5][6]  Sucuk, yağ ve tuz içeren bir besin maddesidir. Ayrıca, kimyon, sumak, kırmızı biber gibi baharatlar ve sarımsak içermektedir.  Sucuktan yapılan sucuklu yumurta, Türkiye'de genellikle kahvaltıda tüketilmektedir.[7]  Sucuk, kuru fasulye, hamur işi yemekler, pizza ve pide yapımında da sıkça kullanılmaktadır.[8][9]",  }),
        ],
      ),
    );
    ;
  }
}
